// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StolenCarPTBackend.Model.Context;

#nullable disable

namespace StolenCarPTBackend.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20221129191252_Brands")]
    partial class Brands
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StolenCarPTBackend.Model.Brands", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Abarth"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Acura"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Bentley"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Bugatti"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Cadillac"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Chrysler"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Citroen"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Cupra"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Dacia"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Daewoo"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Daihatsu"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Datsun"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "DS"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Hummer"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Infiniti"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Isuzu"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Iveco"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Lancia"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Lincoln"
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Lotus"
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Maserati"
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Maybach"
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 41L,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 43L,
                            Name = "MG"
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Mini"
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Pontiac"
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Rolls-Royce"
                        },
                        new
                        {
                            Id = 53L,
                            Name = "Rover"
                        },
                        new
                        {
                            Id = 54L,
                            Name = "Saab"
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Seat"
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Skoda"
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Smart"
                        },
                        new
                        {
                            Id = 58L,
                            Name = "Ssang Yong"
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 60L,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 61L,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 63L,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("StolenCarPTBackend.Model.Districts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Aveiro"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Beja"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Braga"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Bragança"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Castelo Branco"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Coimbra"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Evora"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Faro"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Guarda"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Leiria"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Portalegre"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Santarem"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Setubal"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Viana do Castelo"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Vila Real"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Viseu"
                        });
                });

            modelBuilder.Entity("StolenCarPTBackend.Model.Locations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<long>("district_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("district_id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Águeda",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Albergaria-a-Velha",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Anadia",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Arouca",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Aveiro",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Castelo de Paiva",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Espinho",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Estarreja",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Ílhavo",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Mealhada",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Murtosa",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Oliveira de Azeméis",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Oliveira do Bairro",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Ovar",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Santa Maria da Feira",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "São João da Madeira",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Sever do Vouga",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Vagos",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Vale de Cambra",
                            district_id = 1L
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Aljustrel",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Almodôvar",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Alvito",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Barrancos",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Beja",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Castro Verde",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Cuba",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Ferreira do Alentejo",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Mértola",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Moura",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Odemira",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Ourique",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Serpa",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Vidigueira",
                            district_id = 2L
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Amares",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Barcelos",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Braga",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Cabeceiras de Basto",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Celorico de Basto",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Esposende",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Fafe",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Guimarães",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Póvoa de Lanhoso",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Terras de Bouro",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Vieira do Minho",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Vila Nova de Famalicão",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Vila Verde",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Vizela",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Alfândega da Fé",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Bragança",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Carrazeda de Ansiães",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Freixo de Espada à Cinta",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Macedo de Cavaleiros",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 53L,
                            Name = "Miranda do Douro",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 54L,
                            Name = "Mirandela",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Mogadouro",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Torre de Moncorvo",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Vila Flor",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 58L,
                            Name = "Vimioso",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Vinhais",
                            district_id = 4L
                        },
                        new
                        {
                            Id = 60L,
                            Name = "Belmonte",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 61L,
                            Name = "Castelo Branco",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Covilhã",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 63L,
                            Name = "Fundão",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Idanha-a-Nova",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 65L,
                            Name = "Oleiros",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 66L,
                            Name = "Penamacor",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 67L,
                            Name = "Proença-a-Nova",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 68L,
                            Name = "Sertã",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 69L,
                            Name = "Vila de Rei",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 70L,
                            Name = "Vila Velha de Ródão",
                            district_id = 5L
                        },
                        new
                        {
                            Id = 71L,
                            Name = "Arganil",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 72L,
                            Name = "Cantanhede",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 73L,
                            Name = "Coimbra",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 74L,
                            Name = "Condeixa-a-Nova",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 75L,
                            Name = "Figueira da Foz",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 76L,
                            Name = "Góis",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 77L,
                            Name = "Lousã",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 78L,
                            Name = "Mira",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 79L,
                            Name = "Miranda do Corvo",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 80L,
                            Name = "Montemor-o-Velho",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 81L,
                            Name = "Oliveira do Hospital",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 82L,
                            Name = "Pampilhosa da Serra",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 83L,
                            Name = "Penacova",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 84L,
                            Name = "Penela",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 85L,
                            Name = "Soure",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 86L,
                            Name = "Tábua",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 87L,
                            Name = "Vila Nova de Poiares",
                            district_id = 6L
                        },
                        new
                        {
                            Id = 88L,
                            Name = "Alandroal",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 89L,
                            Name = "Arraiolos",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 90L,
                            Name = "Borba",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 91L,
                            Name = "Estremoz",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 92L,
                            Name = "Évora",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 93L,
                            Name = "Montemor-o-Novo",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 94L,
                            Name = "Mora",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 95L,
                            Name = "Mourão",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 96L,
                            Name = "Portel",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 97L,
                            Name = "Redondo",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 98L,
                            Name = "Reguengos de Monsaraz",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 99L,
                            Name = "Vendas Novas",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 100L,
                            Name = "Viana do Alentejo",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 101L,
                            Name = "Vila Viçosa",
                            district_id = 7L
                        },
                        new
                        {
                            Id = 102L,
                            Name = "Albufeira",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 103L,
                            Name = "Alcoutim",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 104L,
                            Name = "Aljezur",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 105L,
                            Name = "Castro Marim",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 106L,
                            Name = "Faro",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 107L,
                            Name = "Lagoa",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 108L,
                            Name = "Lagos",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 109L,
                            Name = "Loulé",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 110L,
                            Name = "Monchique",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 111L,
                            Name = "Olhão",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 112L,
                            Name = "Portimão",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 113L,
                            Name = "São Brás de Alportel",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 114L,
                            Name = "Silves",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 115L,
                            Name = "Tavira",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 116L,
                            Name = "Vila do Bispo",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 117L,
                            Name = "Vila Real de Santo António",
                            district_id = 8L
                        },
                        new
                        {
                            Id = 118L,
                            Name = "Aguiar da Beira",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 119L,
                            Name = "Almeida",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 120L,
                            Name = "Celorico da Beira",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 121L,
                            Name = "Figueira de Castelo Rodrigo",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 122L,
                            Name = "Fornos de Algodres",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 123L,
                            Name = "Gouveia",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 124L,
                            Name = "Guarda",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 125L,
                            Name = "Manteigas",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 126L,
                            Name = "Mêda",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 127L,
                            Name = "Pinhel",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 128L,
                            Name = "Sabugal",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 129L,
                            Name = "Seia",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 130L,
                            Name = "Trancoso",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 131L,
                            Name = "Vila Nova de Foz Côa",
                            district_id = 9L
                        },
                        new
                        {
                            Id = 132L,
                            Name = "Alcobaça",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 133L,
                            Name = "Alvaiázere",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 134L,
                            Name = "Ansião",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 135L,
                            Name = "Batalha",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 136L,
                            Name = "Bombarral",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 137L,
                            Name = "Caldas da Rainha",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 138L,
                            Name = "Castanheira de Pêra",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 139L,
                            Name = "Figueiró dos Vinhos",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 140L,
                            Name = "Leiria",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 141L,
                            Name = "Marinha Grande",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 142L,
                            Name = "Nazaré",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 143L,
                            Name = "Óbidos",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 144L,
                            Name = "Pedrógão Grande",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 145L,
                            Name = "Peniche",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 146L,
                            Name = "Pombal",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 147L,
                            Name = "Porto de Mós",
                            district_id = 10L
                        },
                        new
                        {
                            Id = 148L,
                            Name = "Alenquer",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 149L,
                            Name = "Amadora",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 150L,
                            Name = "Arruda dos Vinhos",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 151L,
                            Name = "Azambuja",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 152L,
                            Name = "Cadaval",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 153L,
                            Name = "Cascais",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 154L,
                            Name = "Lisboa",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 155L,
                            Name = "Loures",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 156L,
                            Name = "Lourinhã",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 157L,
                            Name = "Mafra",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 158L,
                            Name = "Odivelas",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 159L,
                            Name = "Oeiras",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 160L,
                            Name = "Sintra",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 161L,
                            Name = "Sobral de Monte Agraço",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 162L,
                            Name = "Torres Vedras",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 163L,
                            Name = "Vila Franca de Xira",
                            district_id = 11L
                        },
                        new
                        {
                            Id = 164L,
                            Name = "Alter do Chão",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 165L,
                            Name = "Arronches",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 166L,
                            Name = "Avis",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 167L,
                            Name = "Campo Maior",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 168L,
                            Name = "Castelo de Vide",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 169L,
                            Name = "Crato",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 170L,
                            Name = "Elvas",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 171L,
                            Name = "Fronteira",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 172L,
                            Name = "Gavião",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 173L,
                            Name = "Marvão",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 174L,
                            Name = "Monforte",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 175L,
                            Name = "Nisa",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 176L,
                            Name = "Ponte de Sor",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 177L,
                            Name = "Portalegre",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 178L,
                            Name = "Sousel",
                            district_id = 12L
                        },
                        new
                        {
                            Id = 179L,
                            Name = "Amarante",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 180L,
                            Name = "Baião",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 181L,
                            Name = "Felgueiras",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 182L,
                            Name = "Gondomar",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 183L,
                            Name = "Lousada",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 184L,
                            Name = "Maia",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 185L,
                            Name = "Marco de Canaveses",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 186L,
                            Name = "Matosinhos",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 187L,
                            Name = "Paços de Ferreira",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 188L,
                            Name = "Paredes",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 189L,
                            Name = "Penafiel",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 190L,
                            Name = "Porto",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 191L,
                            Name = "Póvoa de Varzim",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 192L,
                            Name = "Santo Tirso",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 193L,
                            Name = "Trofa",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 194L,
                            Name = "Valongo",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 195L,
                            Name = "Vila do Conde",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 196L,
                            Name = "Vila Nova de Gaia",
                            district_id = 13L
                        },
                        new
                        {
                            Id = 197L,
                            Name = "Abrantes",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 198L,
                            Name = "Alcanena",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 199L,
                            Name = "Almeirim",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 200L,
                            Name = "Alpiarça",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 201L,
                            Name = "Benavente",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 202L,
                            Name = "Cartaxo",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 203L,
                            Name = "Chamusca",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 204L,
                            Name = "Constância",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 205L,
                            Name = "Coruche",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 206L,
                            Name = "Entroncamento",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 207L,
                            Name = "Ferreira do Zêzere",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 208L,
                            Name = "Golegã",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 209L,
                            Name = "Mação",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 210L,
                            Name = "Ourém",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 211L,
                            Name = "Rio Maior",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 212L,
                            Name = "Salvaterra de Magos",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 213L,
                            Name = "Santarém",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 214L,
                            Name = "Sardoal",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 215L,
                            Name = "Tomar",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 216L,
                            Name = "Torres Novas",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 217L,
                            Name = "Vila Nova da Barquinha",
                            district_id = 14L
                        },
                        new
                        {
                            Id = 218L,
                            Name = "Alcácer do Sal",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 219L,
                            Name = "Alcochete",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 220L,
                            Name = "Almada",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 221L,
                            Name = "Barreiro",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 222L,
                            Name = "Grândola",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 223L,
                            Name = "Moita",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 224L,
                            Name = "Montijo",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 225L,
                            Name = "Palmela",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 226L,
                            Name = "Santiago do Cacém",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 227L,
                            Name = "Seixal",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 228L,
                            Name = "Sesimbra",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 229L,
                            Name = "Setúbal",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 230L,
                            Name = "Sines",
                            district_id = 15L
                        },
                        new
                        {
                            Id = 231L,
                            Name = "Arcos de Valdevez",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 232L,
                            Name = "Caminha",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 233L,
                            Name = "Melgaço",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 234L,
                            Name = "Monção",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 235L,
                            Name = "Paredes de Coura",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 236L,
                            Name = "Ponte da Barca",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 237L,
                            Name = "Ponte de Lima",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 238L,
                            Name = "Valença",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 239L,
                            Name = "Viana do Castelo",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 240L,
                            Name = "Vila Nova de Cerveira",
                            district_id = 16L
                        },
                        new
                        {
                            Id = 241L,
                            Name = "Alijó",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 242L,
                            Name = "Boticas",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 243L,
                            Name = "Chaves",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 244L,
                            Name = "Mesão Frio",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 245L,
                            Name = "Mondim de Basto",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 246L,
                            Name = "Montalegre",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 247L,
                            Name = "Murça",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 248L,
                            Name = "Peso da Régua",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 249L,
                            Name = "Ribeira de Pena",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 250L,
                            Name = "Sabrosa",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 251L,
                            Name = "Santa Marta de Penaguião",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 252L,
                            Name = "Valpaços",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 253L,
                            Name = "Vila Pouca de Aguiar",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 254L,
                            Name = "Vila Real",
                            district_id = 17L
                        },
                        new
                        {
                            Id = 255L,
                            Name = "Armamar",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 256L,
                            Name = "Carregal do Sal",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 257L,
                            Name = "Castro Daire",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 258L,
                            Name = "Cinfães",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 259L,
                            Name = "Lamego",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 260L,
                            Name = "Mangualde",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 261L,
                            Name = "Moimenta da Beira",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 262L,
                            Name = "Mortágua",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 263L,
                            Name = "Nelas",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 264L,
                            Name = "Oliveira de Frades",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 265L,
                            Name = "Penalva do Castelo",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 266L,
                            Name = "Penedono",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 267L,
                            Name = "Resende",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 268L,
                            Name = "Santa Comba Dão",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 269L,
                            Name = "São João da Pesqueira",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 270L,
                            Name = "São Pedro do Sul",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 271L,
                            Name = "Sátão",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 272L,
                            Name = "Sernancelhe",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 273L,
                            Name = "Tabuaço",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 274L,
                            Name = "Tarouca",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 275L,
                            Name = "Tondela",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 276L,
                            Name = "Vila Nova de Paiva",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 277L,
                            Name = "Viseu",
                            district_id = 18L
                        },
                        new
                        {
                            Id = 278L,
                            Name = "Vouzela",
                            district_id = 18L
                        });
                });

            modelBuilder.Entity("StolenCarPTBackend.Model.Locations", b =>
                {
                    b.HasOne("StolenCarPTBackend.Model.Districts", "Districts")
                        .WithMany()
                        .HasForeignKey("district_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
