// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StolenCarPTBackend.Model.Context;

#nullable disable

namespace StolenCarPTBackend.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StolenCarPTBackend.Model.Districts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Aveiro"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Beja"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Braga"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Bragança"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Castelo Branco"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Coimbra"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Evora"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Faro"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Guarda"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Leirua"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Portalegre"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Santarem"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Setubal"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Viana do Castelo"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Vila Real"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Viseu"
                        });
                });

            modelBuilder.Entity("StolenCarPTBackend.Model.Locations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<long>("district_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("district_id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Vila Nova de Famalicao",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Barcelos",
                            district_id = 3L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Trofa",
                            district_id = 13L
                        });
                });

            modelBuilder.Entity("StolenCarPTBackend.Model.Locations", b =>
                {
                    b.HasOne("StolenCarPTBackend.Model.Districts", "Districts")
                        .WithMany()
                        .HasForeignKey("district_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
